COMPONENT_NAME := suas_app_ble_sniffer
COMPONENT_TYPE := application

COMPONENT_SOURCES := main.c \
                     sniffer.c \
                     scanner.c

COMPONENT_INCLUDES := .

include $(BL60X_SDK_PATH)/make_scripts_riscv/component_wrapper.mk
