COMPONENT_NAME := suas_app_ble_sniffer
COMPONENT_TYPE := application

COMPONENT_SOURCES := main.cpp \
                     sniffer.cpp \
                     scanner.cpp

COMPONENT_INCLUDES := .

include $(BL60X_SDK_PATH)/make_scripts_riscv/component_wrapper.mk
